// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseCartService.Data;

#nullable disable

namespace PurchaseCartService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250711081507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("PurchaseCartService.Models.ProductContract", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("VatRate")
                        .HasColumnType("REAL");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Price = 2.0,
                            VatRate = 0.10000000000000001
                        },
                        new
                        {
                            ProductId = 2,
                            Price = 1.5,
                            VatRate = 0.10000000000000001
                        },
                        new
                        {
                            ProductId = 3,
                            Price = 3.0,
                            VatRate = 0.10000000000000001
                        },
                        new
                        {
                            ProductId = 4,
                            Price = 15.9,
                            VatRate = 0.040000000000000001
                        },
                        new
                        {
                            ProductId = 5,
                            Price = 28.0,
                            VatRate = 0.040000000000000001
                        },
                        new
                        {
                            ProductId = 6,
                            Price = 399.99000000000001,
                            VatRate = 0.22
                        },
                        new
                        {
                            ProductId = 7,
                            Price = 899.0,
                            VatRate = 0.22
                        },
                        new
                        {
                            ProductId = 8,
                            Price = 24.949999999999999,
                            VatRate = 0.22
                        },
                        new
                        {
                            ProductId = 9,
                            Price = 49.899999999999999,
                            VatRate = 0.22
                        },
                        new
                        {
                            ProductId = 10,
                            Price = 59.990000000000002,
                            VatRate = 0.22
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
